# Numpy: Arreglos Matriciales

In [ ]:
import numpy as np

In [ ]:
from platform import python_version

print(python_version())

In [ ]:
import sys
sys.executable

Más información: 
https://numpy.org/doc/stable/reference/?v=20230207185142

El principal objetivo de la librería Numpy son arreglos homogéneos multidimensionales. Es decir, es una tabla de elementos, todos con el mismo tipo e indexador por *tuple* de enteros positivos. 

La dimensiones en numpy se llaman **ejes**(axes); el número de ejes se llama **rango**(rank)

La clase de arreglos en Numpy se conocen como **ndarrays** o más comúnmente, **arrays**. Un `numpy.array` no es un `array.array` de la librería estándar de Python (homogéneos, pero unidemensionales y con menor funcionalidad que numpy). 

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

In [ ]:
dir(arr1)

In [ ]:
arr1[(1,2)]

In [ ]:
arr1.ndim

In [ ]:
arr1.shape

In [ ]:
arr1=np.array(

    [
        [1,2,3],
        [4,5,6]

    ]

)
arr1

In [ ]:
#¿Cómo se le puede agregar más dimensiones?

arr1=np.array(
   [ 
    [
        [1,2,3],
        [4,5,6]

    ]
   ]

)
arr1

In [ ]:
arr1.ndim

In [ ]:
arr1.shape

In [ ]:
arr1[(0,1,2)]

In [ ]:
arr1=np.array(
[
   [ 
    [
        [1,2,3],
        [4,5,6]

    ]
   ]
]
)
arr1

In [ ]:
arr1.ndim

In [ ]:
arr1.shape

In [ ]:
arr1=np.array(
[
   [ 
    [
        [1,2,3],
        [4,5,6]

    ],

    [
        [1,2,3],
        [4,5,6]

    ]
   ]
]
)
arr1

In [ ]:
arr1.ndim

In [ ]:
arr1.shape

In [ ]:
arr1=np.array(
[
   [ 
    [
        [1,2,3],
        [4,5,6]

    ],

    [
        [1,2,3],
        [4,5]

    ]
   ]
]
)
arr1

In [ ]:
arr1=np.array(
[
   [ 
    [
        [1,2,3]
    ],

    [
        [1,2,3],
        [4,5,6]

    ]
   ]
]
)
arr1

Una de las principales ventajas de usar `numpy` es el poder de usar vectorización de funciones aplicadas a un `numpy.array`. Esto implica poder aplicar una función a cada `numpy.array` **sin necesidad de expresar un for loop**, lo cual hace trabajar con este tipo de funciones de manera más eficiente. 

In [ ]:
#Ejemplo
#sumar los cuadrados del 1 a 10_000_000

In [ ]:
%%time
sum([i**2 for i in range(10_000_000)])

In [ ]:
%%time
(np.arange(10_000_000)**2).sum() #97% más rápido.  15ms versus 457ms

### Propiedades Principales de `ndarray`. 

In [ ]:
arr1.ndim

In [ ]:
arr1.shape

In [ ]:
arr1.dtype

### Creación de Ndarrays

## `np.array`

Un `ndarray` se crea mediante `array` cuyo primer parámetro es la lista (o tuple) de elementos en el arreglo. Por convención, se importará la librería de numpy con `np`.

In [ ]:
arr=np.array([[2,8],[8,1]])
arr

In [ ]:
arr.shape

In [ ]:
arr.ndim

## Operaciones y Propiedades de Numpy Arrays

In [ ]:
arr

In [ ]:
arr+1

In [ ]:
arr**2

In [ ]:
arr*4

In [ ]:
arr<=4

#### `np.arange` , `np.linspace`. 
Podemos crear rangos de números $[a,b)$ usando la función `arange` (análogo de `range` en python) 

Usamos la función `linspace` cuando deseamos un arreglo de $n$ elementos entre $a$  y $b$ inclusivo; $a<b$

In [ ]:
np.arange(2,11,2) 

In [ ]:
np.linspace(1,10,20)

In [ ]:
#lo que hace arriba es ir de 1 al 10 en 20 observaciones incluyéndolas
1+(1*(9/19))

In [ ]:
#a diferencia de un range, np.range nos permite tomar psaso fracdionados
np.arange(1,11,0.5)

In [ ]:
for x in range(1,11,0.5):
    print(x)

## Ejercicio
Crea un numpy array con 100elementos $\{x_i\}_{i=0}^{99}$
$$
    x_i = i (i + 100) \ \forall \ i \in \{0, \ldots, 99\}
$$

e.g., $x_{99} = 19701$; $x_{10} = 1100$ 

In [ ]:
(np.arange(100)+100)*np.arange(100)

# Índices 

Podemos seleccionar múltiples filas usando dobles corchetes

In [ ]:
arr=np.arange(25)
arr

In [ ]:
arr.shape

In [ ]:
arr.ndim

In [ ]:
arr=np.arange(25).reshape(5,5)
arr

In [ ]:
arr.shape

In [ ]:
arr.ndim

In [ ]:
arr=np.arange(25).reshape(5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1)
arr

In [ ]:
arr=np.arange(25).reshape(5,5)
arr

In [ ]:
arr[0,:]

In [ ]:
arr[1,:]

In [ ]:
arr[:,-1] #última columna

In [ ]:
arr[-1,-3:1:-1]
#última fila
#que vaya de la posicion -3 a la posiion 1 (sin tocarla)
#-1 final en reversa

# Broadcasting

**Broadcasting** (difusión) es la manera en que numpy manipula *arrays* con diferentes dimensiones durante operaciones aritméticas. Para $A$ y $B$, dos dimensiones son compatibles cuando: 
1. Son iguales
2. Una dimensión es igual a 1

In [ ]:
A=np.arange(25).reshape(5,5)
B=np.arange(5).reshape(1,5)

In [ ]:
A+B

In [ ]:
A*B

In [ ]:
A=np.arange(6).reshape(2,3)
B=np.arange(6).reshape(3,2)

In [ ]:
A

In [ ]:
B

In [ ]:
A@B

####  `np.zeros`

In [ ]:
np.zeros(shape=10)

####  `np.ones`

In [ ]:
np.ones(shape=10)

####  `np.triu` , `np.tril`

In [ ]:
np.triu([1,2,3,4,6],k=0)

####  `np.identity`

In [ ]:
np.identity(5)

# Ejercicio
Crea un numpy array en $\mathbb{R}^{10\times 10}$ tal que

$$
x_{i,j} = 
\begin{cases}
    2i & \forall \ i = j \\
    0 & \forall \ i \neq j
\end{cases}
$$

Considera $i, j \in \{1, \ldots, 10\}$

In [ ]:
np.identity(10)*np.arange(2,22,2)

### Dimensiones de numpy arrays
Los `ndarrays` son $n$ dimensionales, lo que significa que podemos crear un arreglo $n$-dimensional siguiendo la misma lógica

# Métodos de un Numpy array

In [ ]:
a2=np.random.randint(-100,100,10)
a2

In [ ]:
dir(a2)

In [ ]:
a2.sum()

# Otros métodos de Numpy

Numpy nos permite aplicar una función en un eje particular usando

`np.apply_along_axis(func1d,axis,arr,*args,**kwargs)`;

donde `func1d` es una $f:\mathbb{R}^n \to \mathbb{R}^m$;

`axis`es el eje a ejecutar: 0 se usa para cada fila de una columna (sobre las columnas) y 1 (se usa para cada columna 
de una fila (sobre las filas)

`arr` es el numpy array a manipular


## Nota 
Al usar la función `np.apply_along_axis`, numpy aplica implícitamente un *for loop* en python sobre el eje que decidamos. Usar `np.apply_along_axis` no es la manera más efciente al realizaar este tipo de operaciones. Siempre que exista una operación equivalente de python en numpy, es recomendable usar la función de numpy. 

Por ejemplo, el equivalente de `sorted` en python es `np.sort` en numpy

# Ejercicios 
1. Escribe la función `suma_producto` que tome un numpy array con dos dimensiones de shape `(n, n)`, el índice de una fila, el índice de una columna, y calcule la suma de multiplicar cada elemento de la columna seleccionada por cada elemento de la fila seleccionada.

Por ejemplo, te tener una matriz
```
a1 = np.array([[2, 3, 3],
               [4, 3, 3],
               [5, 3, 1]])
```

Calcular ```suma_producto(a1, 0, 2)``` consideraría la primera fila (`[2, 3, 3]`), la última columna (`[3, 3, 1]`)  y realizaría la siguiente operación:
```
2 * 3 + 3 * 3 + 3 * 1 = 18
```

```python
>>> a2 = np.array([[2, 3],
                   [3, 4]])
>>> suma_producto(a2, 0, 0)
13

a3 = np.array([[2, 3, 3, 4],
               [3, 3, 5, 3],
               [1, 2, 2, 3],
               [5, 5, 5, 5]])
>>> suma_producto(a3, 2, 1)
28

```

In [ ]:
def suma_producto(arr, fila, col):

    fila_vec=arr[fila,:]

    col_vec=arr[:,col]

    return int(np.dot(fila_vec,col_vec))
    

In [ ]:
a1 = np.array([[2, 3, 3],
               [4, 3, 3],
               [5, 3, 1]])

In [ ]:
suma_producto(a1,0,2)

2. escribe la función (`suma_pos`) que tome un numpy array y regrese la suma de todos los elementos positivos del array

```python
>>> a1 = np.array([[ 0,  4,  1],
                   [-3, -3,  1],
                   [-3,  2, -3]])
>>> suma_pos(a1)
8
```

3. Escribe la función `cercano` que tome un numpy array unidimensional, un número base y encuentre el (los) número(s) que más se aproxime (en valor aboluto) al número base

```python
a1 = np.arrray([-25,  27,   8, -12,  20,   8,  29, -28,   9, -12, -23, -26,  20,-22, -29])
>>> cercano(a1, 10)
array([9])
>>> cercano(a1, -3)
array([-12, -12])
```

4. Define la función `pascal` que cree el triangulo de pascal a $n\geq 2$ terminos en arreglo de lista de listas. 

```python
>>> pascal(3)
[[1],
 [1, 1],
 [1, 2, 1]]
>>> pascal(12)
[[1],
 [1, 1],
 [1, 2, 1],
 [1, 3, 3, 1],
 [1, 4, 6, 4, 1],
 [1, 5, 10, 10, 5, 1],
 [1, 6, 15, 20, 15, 6, 1],
 [1, 7, 21, 35, 35, 21, 7, 1],
 [1, 8, 28, 56, 70, 56, 28, 8, 1],
 [1, 9, 36, 84, 126, 126, 84, 36, 9, 1],
 [1, 10, 45, 120, 210, 252, 210, 120, 45, 10, 1],
 [1, 11, 55, 165, 330, 462, 462, 330, 165, 55, 11, 1]]
```

5. Escribe un programa `filter_sum(arr, f)` que cree un _filtro_ de suma para un numpy array de dos dimensiones con `arr.shape[0] == arr.shape[1]`. Un filtro de tamaño `f` captura los elementos de `arr` con una _ventana_ de tamaño `(f, f)` y suma los valores para arrojar un nuevo resultado dentro de una matriz final.

Por ejemplo, dado el array
```
[[ 6,  7, 19, 19,  7],
[ 3,  8, 19,  8,  5],
[19,  9,  2, 11, 15],
[ 5, 15,  6, 17, 17],
[17,  2,  1, 17, 12]]
```

Las _ventanas_ de la matriz, con `f=3`, serían
```
[[ 6  7 19]
 [ 3  8 19]
 [19  9  2]]

[[ 7 19 19]
 [ 8 19  8]
 [ 9  2 11]]
 
 ...
 
 [[ 2 11 15]
 [ 6 17 17]
 [ 1 17 12]]
```

Con valores `92, 105, ..., 98`

y la matriz resultante sería

```
[[ 92., 102., 105.],
[ 86.,  95., 100.],
[ 76.,  80.,  98.]])
```

[Imagen adjunta removida para reducir tamaño del archivo]